from __future__ import annotations

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from fake_openai_server import FakeOpenAIServer
from twin.cli import app
from twin.core.prompts import load_prompt
from twin.core.schemas import ContextTurn, Pair
from twin.ingest.style_profile import (
    STOPWORDS,
    StyleProfileExistsError,
    StyleProfileResult,
    build_messages,
    count_rules,
    read_style_profile,
    render_examples,
    reply_style_stats,
    sample_pairs,
    tokenize,
    top_words,
    write_style_profile,
)

YEAR = 365 * 86400
BASE = 1609459200  # 2021-01-01


def pair(index: int, reply: str, year_offset: int = 0, partner: str = "как дела?") -> Pair:
    ts = BASE + year_offset * YEAR + index * 3600
    return Pair(
        pair_id=f"1002:{index}",
        chat_id=1002,
        conversation_id="1002:0",
        ts=ts,
        period=f"{2021 + year_offset}-01",
        context=[
            ContextTurn(sender_name="Радомир", is_me=True, text="своё"),
            ContextTurn(sender_name="Злата", is_me=False, text=partner),
        ],
        reply=reply,
        reply_message_ids=[index],
    )


def test_sample_is_stratified_by_year_and_deterministic() -> None:
    pairs = [pair(i, f"ответ {i}", year_offset=i % 3) for i in range(30)]  # 10 per year
    sample = sample_pairs(pairs, 6, seed=1)
    assert [p.period[:4] for p in sample] == ["2021", "2021", "2022", "2022", "2023", "2023"]
    assert sample == sample_pairs(list(reversed(pairs)), 6, seed=1)
    assert sample != sample_pairs(pairs, 6, seed=2)
    assert len(sample_pairs(pairs, 500, seed=1)) == 30


def test_tokenize_and_top_words_skip_stopwords() -> None:
    assert tokenize("Ну да, Я-то ЗНАЮ 42 ok") == ["ну", "да", "то", "знаю", "ok"]
    pairs = [pair(1, "ну это жесть"), pair(2, "жесть какая"), pair(3, "это да")]
    assert top_words(pairs, 2) == [("жесть", 2), ("какая", 1)]
    assert "это" in STOPWORDS and "жесть" not in STOPWORDS


def test_reply_style_stats() -> None:
    pairs = [pair(1, "Да."), pair(2, "ну что?\nпойдём 😂"), pair(3, "ок)"), pair(4, "ЛОЛ 10 раз")]
    stats = reply_style_stats(pairs)
    assert stats["replies"] == 4
    assert stats["emoji_pct"] == 25.0 and stats["question_pct"] == 25.0
    assert stats["multiline_pct"] == 25.0 and stats["ends_with_period_pct"] == 25.0
    assert stats["bracket_smile_pct"] == 25.0 and stats["starts_uppercase_pct"] == 50.0
    assert stats["all_caps_word_pct"] == 25.0 and stats["digits_pct"] == 25.0
    assert stats["le_10_chars_pct"] == 75.0  # "ЛОЛ 10 раз" is exactly 10 chars


def test_render_examples_uses_last_partner_turn_and_truncates() -> None:
    long_question = "в" * 400
    text = render_examples([pair(1, "да\nконечно", partner=long_question)], "Радомир")
    assert text.startswith("1. Собеседник: " + "в" * 299 + "…")
    assert text.endswith("Радомир: да / конечно")


def test_build_messages_fills_every_placeholder() -> None:
    pairs = [pair(i, f"ответ номер {i}") for i in range(5)]
    messages = build_messages(load_prompt("style_profile_v1"), "Радомир", pairs, pairs[:2])
    assert [m["role"] for m in messages] == ["system", "user"]
    user = messages[1]["content"]
    assert "${" not in user and "Радомир" in user
    assert "2 примеров" in user and "1. Собеседник" in user and "2. Собеседник" in user
    assert "медиана длины" in user and "топ-50 слов" in user


def test_count_rules() -> None:
    assert count_rules("- a\n- b\n* c\n1. d\n2) e\nтекст\n") == 5


def test_write_guard_and_read_strips_header(tmp_path: Path) -> None:
    result = StyleProfileResult("- правило\n", 1, 3, "style_profile_v1", "m", 1, 1, 5)
    target = tmp_path / "style_profile.md"
    write_style_profile(target, result, "abc123", force=False)
    text = target.read_text(encoding="utf-8")
    assert text.startswith("<!-- generated by `twin style-profile`") and "abc123" in text
    assert read_style_profile(target) == "- правило\n"
    with pytest.raises(StyleProfileExistsError):
        write_style_profile(target, result, "abc123", force=False)
    write_style_profile(target, result, "def456", force=True)
    assert "def456" in target.read_text(encoding="utf-8")


RULES = "\n".join(f"- правило {i}" for i in range(1, 23)) + "\n"


def test_cli_end_to_end_with_fake_server(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, synthetic_export_path: Path
) -> None:
    runner = CliRunner()
    monkeypatch.setenv("DATA_DIR", str(tmp_path / "data"))
    monkeypatch.setenv("TWIN_SENDER_ID", "1001")
    monkeypatch.delenv("RAW_EXPORT_PATH", raising=False)
    config = tmp_path / "data.yaml"
    config.write_text("filters:\n  min_date: null\n", encoding="utf-8")
    assert (
        runner.invoke(
            app, ["ingest", "--export", str(synthetic_export_path), "--config", str(config)]
        ).exit_code
        == 0
    )
    monkeypatch.setenv("LLM_API_KEY", "sk-test")
    monkeypatch.setenv("STYLE_PROFILE_MODEL", "anthropic/fake")
    for key in ("TWIN_NAME",):
        monkeypatch.delenv(key, raising=False)

    with FakeOpenAIServer(reply=RULES) as server:
        monkeypatch.setenv("LLM_BASE_URL", server.base_url)
        missing = runner.invoke(app, ["style-profile"])
        assert missing.exit_code == 1 and "TWIN_NAME" in missing.output
        assert server.requests == []

        monkeypatch.setenv("TWIN_NAME", "Радомир")
        first = runner.invoke(app, ["style-profile", "--sample-size", "3"])
        assert first.exit_code == 0, first.output
        assert "22 rules" in first.output and "sample 3 replies" in first.output
        body = server.requests[0]
        assert body["model"] == "anthropic/fake" and body["temperature"] == 0.3
        assert "Радомир" in body["messages"][1]["content"]
        target = tmp_path / "data" / "processed" / "style_profile.md"
        manifest = json.loads(
            (tmp_path / "data" / "processed" / "dataset_manifest.json").read_text()
        )
        assert manifest["dataset_version"] in target.read_text(encoding="utf-8")
        assert read_style_profile(target) == RULES

        second = runner.invoke(app, ["style-profile"])
        assert second.exit_code == 1 and "--force" in second.output
        assert len(server.requests) == 1  # refused before calling the model

        forced = runner.invoke(app, ["style-profile", "--force", "--sample-size", "2"])
        assert forced.exit_code == 0, forced.output
        assert len(server.requests) == 2
